version: '3.8'

services:
  # coineus-api
  coineus-api:
    image: safderun/coineus-server
    container_name: coineus-server
    environment:
      POSTGRE_DB_URI: postgres://postgres:postgres123@postgres:5432/coineusdb
      JWT_SIGNING_KEY: mysupersecretkey
      JWT_EXP_TIME: 96
      RETRY_COUNT: 5
      RETRY_COOLDOWN: 2
      PRICE_SERVICE_BASE_URL: http://coineus-price-service
      PORT: 80
    depends_on:
      - postgres
    networks:
      - coineus_network
    ports:
      - 8080:80


  # db
  postgres:
    image: postgres:14
    container_name: coineus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: coineusdb
    healthcheck:
      test: ["CMD", "pg_isready", "-u", "postgres", "-d", "coineusdb"]
      interval: 3s
      retries: 5
    ports:
        - 5432:5432
    volumes:
      - ./docker/script/init.sql:/docker-entrypoint-initdb.d/init.sql
      - coineus-postgre-data:/var/lib/postgresql/data
    restart: always
    networks:
      - coineus_network



networks:
    coineus_network:
      name: coineus_network
      driver: bridge

volumes:
  coineus-postgre-data:
    name: coineus-postgre-data
    driver: local
