version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: coineusdb
    healthcheck:
      test: ["CMD", "pg_isready", "-u", "postgres", "-d", "coineusdb"]
      interval: 5s
      retries: 5
    ports:
        - 5432:5432
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
      - coineus-postgre-data:/var/lib/postgresql/data
    restart: always
    networks:
      - coineus_network

networks:
  coineus_network:
    external: true

volumes:
  coineus-postgre-data:
    external: true