version: '3.8'

services:
  # coineus-api
  coineus-api:
    image: "safderun/coineus-server:latest"
    container_name: coineus-server
    environment:
      POSTGRE_DB_URI: postgres://postgres:postgres123@postgres:5432/coineusdb
      JWT_SIGNING_KEY: mysupersecretkey
      JWT_EXP_TIME: 96
      RETRY_COUNT: 5
      RETRY_COOLDOWN: 2
      PRICE_SERVICE_BASE_URL: coineus-price-service/
      PORT: 80
    networks:
      - coineus_network
    ports:
      - 80:80



networks:
    coineus_network:
      external: true
      